name: Python Package CI/CD

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests targeting the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Check out the repository

    - name: Set up Python
      uses: actions/setup-python@v2  # Set up Python environment
      with:
        python-version: '3.8'  # Use Python 3.8 or whichever version you're using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install -r requirements.txt  # Install the dependencies

    - name: Run tests (optional)
      run: |
        # If you have tests, you can run them here
        # Example: pytest
        echo "No tests defined"  # Replace this with the actual test command (e.g., pytest)

    - name: Build and upload package to PyPI (optional)
      if: github.ref == 'refs/heads/main'  # Only run this on the main branch
      run: |
        python setup.py sdist bdist_wheel  # Build source distribution and wheel
        pip install twine  # Install Twine
        twine upload dist/*  # Upload package to PyPI

    - name: Clean up
      run: rm -rf dist  # Clean up build artifacts
